### ISSUE TITLE
no_std

### ISSUE THREAD

**Issue by wackazong** [audunhalland/entrait#33]
no_std support is pretty easy, would you like a pull request? See here:

https://github.com/ibexus-platform/entrait
https://github.com/ibexus-platform/implementation

**Comment by audunhalland** [comment]
I'd accept.. Haven't verified this, but: I don't think there even needs to be a `std` feature flag for any of these two crates. Just add `#![no_std]` at the top of both crates, use `::core` instead of `::std` and that's even non-breaking changes in both cases and could just release minor versions updates. Do you agree?

**Comment by audunhalland** [comment]
both crates published with minor version bumps
